### ISSUE TITLE
GLint64 and GLuint64

### ISSUE THREAD

**Issue by El-Cerdo** [beyondmarc/opengl.vim#3]
Hi,

great work, but you have forgotten the data types GLint64 and GLuint64. See [https://www.opengl.org/wiki/OpenGL_Type]

Greetings,
Cerdo

**Comment by beyondmarc** [comment]
Fixed in [94be14](https://github.com/beyondmarc/opengl.vim/commit/94be14c22679e61f43580421e7f2d039f567f659).

BTW, you know I accept pull requests, right? ;)

Thanks!
